utkarsh-shekhar/basic-programs

README.md

For issue  [1](https://github.com/utkarsh-shekhar/basic-programs/issues/1)

Updated readme file for basic-programs

---

README.md

For issue [2](https://github.com/utkarsh-shekhar/basic-programs/issues/3)

updated python folder structure

---

C/Factorial.c

Added factorial program in for #9

Added factorial in C

---

README.md

Added formatting and grammatical changes

---

C++/factorial.cpp
c/Recursion/sum_of_digits_with_recursion.c

Adding factorial code in C++

---

php/fizz-buzz.php

Add fizz buzz test using php #24

add fizz buzz test using php

---

PHP/factorial.php

Add factorial using PHP as in #9

Add factorial using PHP

---

javascript/Strict vs Type Converting Equality/equality.js
javascript/readme.md

Add Comparision btw Strict and Normal Equality

---

python/recursion/factorial.py

Added a factorial program that uses recursion for Python

---

javascript/Callbacks/simple-callback.js

Add callback example using JS as in #32

JavaScript callback example

---

C++/fizz-buzz.cpp

Added Fizz Buzz test for C++ 

---

java/Multi threading/Create thread and run.java
java/Multi threading/Thread extension.java

Add a program using multi threading #12

---

python/factorial.py

For Issue [9](https://github.com/utkarsh-shekhar/basic-programs/issues/9)

Added factorial.py

---

javascript/Factorial/imperative-factorial.js
javascript/Recursion/recursive-factorial.js

Add factorial examples using JS as in #9, and #11 since I already added the a recursive version of the same program.

Add JavaScript factorial examples

---

java/method-overloading.java

Issue: https://github.com/utkarsh-shekhar/basic-programs/issues/31

Add method overloading example in Java.

---

javascript/recursion.js

JavaScript example to show recursion to calculate the sum of an array

Added JavaScript recursion example

---

java/recursion/Factorial.java
java/recursion/NCR.java

Java_Program_to_Find_Factorials_Recursion

---

javascript/method-overloading.js

Hey! 👋 
I've added an example for method overloading in JavaScript, as per #31!
I've written comments where appropriate — I think it's detailed enough, but happy to make changes.
Probably worth prefacing that method overloading isn't encourage in JavaScript, and should only be used where there aren't alternatives!
✌️

Add method overloading example in JavaScript

---

java/fizz-buzz.java

Add FizzBuzz test for Java

---

go/largestPrimeFactor.go
go/sumMultiple3and5.go

Add golang recursion examples

---

swift/method-overloading.swift

Added an example of method overloading in Swift programming language. This example should work with Swift version 3 and 4

Added method overloading example in swift programming language

---

c/fizz-buzz.c

Added Fizz-Buzz in C - issue #24

---

java/recursion/GCD.java

Add a GCD recursive function in Java

---

ruby/MethodOverloading.rb

Added Method overloading program in RUBY

Added Method Overloading program in Ruby

---

python/palindrome.py

Add Palindrome function in python. 
Solving issue 72
https://github.com/utkarsh-shekhar/basic-programs/issues/72

Add palindrome function in python

---

java/Palindrome.java

Solving issue 78
https://github.com/utkarsh-shekhar/basic-programs/issues/78 
Kindly request to check and merge pull request.

Add Palindrome function in Java

---

kotlin/recursion/Gcd.kt

Kotlin recursion implementation of gcd for #11

Addition of gcd recursion Kotlin implementation

---

javascript/rest-params.js

Created A example using Rest Params with Javascript

Add Rest Params Function Javascript

---

python/fizz_buzz_interactive.py

Participating in Hacktoberfest, learning how to use GitHub. Thanks in advance for the opportunity to participate!

Python fizz buzz with user interaction

---

java/Student.java

Creates a Student class, and overloads the constructor method.

Student.java

---

php/is_prime.php

This pull request created for the issue no 91

is_prime in php

---

python/recursion/quicksort.py
python/recursion/quicksort_tests.py

Added randomised quick sort implementation in python to recursive programs

Added quick sort implementation to recursive programs

---

java/CompositeMagic.java

This is a java program to check if the numbers entered are composite magic numbers or not, its counts and prints the frequency of all composite magic numbers present within the given range

added CompositeMagic.java

---

java/counting_sort.java

counting sort solution

---

CountingSort.java

This is for hacktober. The function has been created in java as instructed and also called in main method to see how it works. Please review it. Thanks you.

Implementation of Counting Sort in Java From Issue #105

---

java/Armstrong.java
java/InsertionSort.java
java/Java Program to divide a string in 'N' equal parts.java
java/MergeSort.java
java/QuickSort.java
java/Selection Sort.java

Quicksort algorithm is one of the most used sorting algorithms, especially to sort large lists/arrays. Quicksort is a divide and conquer algorithm, which means the original array is divided into two arrays, each of them is sorted individually, and then sorted output is merged to produce the sorted array. On average, it has O(n log n) complexity, making quicksort suitable for sorting big data volumes.

adding a Algorithm

---

java/Insert_array.java

Added program to insert element into an existing array

To insert element in existing array
